CREATE TABLE bill
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_meter_id BIGINT,
    meter_reading_id  BIGINT,
    tax               DOUBLE PRECISION,
    total_amount      DOUBLE PRECISION,
    due_date          TIMESTAMP WITHOUT TIME ZONE,
    bill_status       SMALLINT,
    generated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bill PRIMARY KEY (id)
);

CREATE TABLE bpo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state_id  BIGINT,
    bpo_name  VARCHAR(255),
    is_active BOOLEAN,
    CONSTRAINT pk_bpo PRIMARY KEY (id)
);

CREATE TABLE bpo_area
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bpo_id  BIGINT,
    area_id BIGINT,
    CONSTRAINT pk_bpo_area PRIMARY KEY (id)
);

CREATE TABLE complaint
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id       BIGINT,
    customer_meter_id BIGINT,
    description       VARCHAR(255),
    complaint_status  SMALLINT,
    personnel_id      BIGINT,
    technician_id     BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    resolved_at       TIMESTAMP WITHOUT TIME ZONE,
    bpo_id            BIGINT,
    CONSTRAINT pk_complaint PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT,
    customer_name VARCHAR(255),
    address       VARCHAR(255),
    state_id      BIGINT,
    district_id   BIGINT,
    city_id       BIGINT,
    area_id       BIGINT,
    pincode       VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE customer_meter
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    connection_id     BIGINT,
    meter_no          VARCHAR(255),
    installation_date TIMESTAMP WITHOUT TIME ZONE,
    meter_status      VARCHAR(255),
    CONSTRAINT pk_customer_meter PRIMARY KEY (id)
);

CREATE TABLE customer_meter_connection
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id   BIGINT,
    meter_type_id BIGINT,
    CONSTRAINT pk_customer_meter_connection PRIMARY KEY (id)
);

CREATE TABLE meter_billing_plan
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meter_type_id   BIGINT,
    rate_per_unit   DOUBLE PRECISION,
    fixed_charge    DOUBLE PRECISION,
    photos_required INTEGER,
    photos_interval INTEGER,
    CONSTRAINT pk_meter_billing_plan PRIMARY KEY (id)
);

CREATE TABLE meter_reading
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_meter_id BIGINT,
    captured_by       BIGINT,
    units_consumed    BIGINT,
    reading_date      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_meter_reading PRIMARY KEY (id)
);

CREATE TABLE meter_reading_photo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    photo_url   VARCHAR(255),
    captured_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_meter_reading_photo PRIMARY KEY (id)
);

CREATE TABLE meter_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meter_name  VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_meter_type PRIMARY KEY (id)
);

CREATE TABLE tenant_area
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area_name VARCHAR(255),
    city_id   BIGINT,
    pincode   INTEGER,
    CONSTRAINT pk_tenant_area PRIMARY KEY (id)
);

CREATE TABLE tenant_city
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name   VARCHAR(255),
    district_id BIGINT,
    CONSTRAINT pk_tenant_city PRIMARY KEY (id)
);

CREATE TABLE tenant_district
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district_name VARCHAR(255),
    state_id      BIGINT,
    CONSTRAINT pk_tenant_district PRIMARY KEY (id)
);

CREATE TABLE tenant_refresh_token
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    token    TEXT,
    CONSTRAINT pk_tenant_refresh_token PRIMARY KEY (id)
);

CREATE TABLE tenant_state
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state_name VARCHAR(255),
    CONSTRAINT pk_tenant_state PRIMARY KEY (id)
);

CREATE TABLE tenant_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    is_enabled BOOLEAN,
    CONSTRAINT pk_tenant_users PRIMARY KEY (id)
);

CREATE TABLE tenant_users_roles
(
    tenant_users_id BIGINT NOT NULL,
    roles           VARCHAR(255)
);

ALTER TABLE bill
    ADD CONSTRAINT FK_BILL_ON_CUSTOMER_METER FOREIGN KEY (customer_meter_id) REFERENCES customer_meter (id);

ALTER TABLE bill
    ADD CONSTRAINT FK_BILL_ON_METER_READING FOREIGN KEY (meter_reading_id) REFERENCES meter_reading (id);

ALTER TABLE bpo_area
    ADD CONSTRAINT FK_BPO_AREA_ON_AREA FOREIGN KEY (area_id) REFERENCES tenant_area (id);

ALTER TABLE bpo_area
    ADD CONSTRAINT FK_BPO_AREA_ON_BPO FOREIGN KEY (bpo_id) REFERENCES bpo (id);

ALTER TABLE bpo
    ADD CONSTRAINT FK_BPO_ON_STATE FOREIGN KEY (state_id) REFERENCES tenant_state (id);

ALTER TABLE complaint
    ADD CONSTRAINT FK_COMPLAINT_ON_BPO FOREIGN KEY (bpo_id) REFERENCES bpo (id);

ALTER TABLE complaint
    ADD CONSTRAINT FK_COMPLAINT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE complaint
    ADD CONSTRAINT FK_COMPLAINT_ON_CUSTOMER_METER FOREIGN KEY (customer_meter_id) REFERENCES customer_meter (id);

ALTER TABLE complaint
    ADD CONSTRAINT FK_COMPLAINT_ON_PERSONNEL FOREIGN KEY (personnel_id) REFERENCES tenant_users (id);

ALTER TABLE customer_meter_connection
    ADD CONSTRAINT FK_CUSTOMER_METER_CONNECTION_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE customer_meter_connection
    ADD CONSTRAINT FK_CUSTOMER_METER_CONNECTION_ON_METER_TYPE FOREIGN KEY (meter_type_id) REFERENCES meter_type (id);

ALTER TABLE customer_meter
    ADD CONSTRAINT FK_CUSTOMER_METER_ON_CONNECTION FOREIGN KEY (connection_id) REFERENCES customer_meter_connection (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_AREA FOREIGN KEY (area_id) REFERENCES tenant_area (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CITY FOREIGN KEY (city_id) REFERENCES tenant_city (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_DISTRICT FOREIGN KEY (district_id) REFERENCES tenant_district (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_STATE FOREIGN KEY (state_id) REFERENCES tenant_state (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_USER FOREIGN KEY (user_id) REFERENCES platform_users (id);

ALTER TABLE meter_billing_plan
    ADD CONSTRAINT FK_METER_BILLING_PLAN_ON_METER_TYPE FOREIGN KEY (meter_type_id) REFERENCES meter_type (id);

ALTER TABLE meter_reading
    ADD CONSTRAINT FK_METER_READING_ON_CUSTOMER_METER FOREIGN KEY (customer_meter_id) REFERENCES customer_meter (id);

ALTER TABLE tenant_area
    ADD CONSTRAINT FK_TENANT_AREA_ON_CITY FOREIGN KEY (city_id) REFERENCES city (id);

ALTER TABLE tenant_city
    ADD CONSTRAINT FK_TENANT_CITY_ON_DISTRICT FOREIGN KEY (district_id) REFERENCES district (id);

ALTER TABLE tenant_district
    ADD CONSTRAINT FK_TENANT_DISTRICT_ON_STATE FOREIGN KEY (state_id) REFERENCES state (id);

ALTER TABLE tenant_users_roles
    ADD CONSTRAINT fk_tenantusers_roles_on_tenant_users FOREIGN KEY (tenant_users_id) REFERENCES tenant_users (id);