CREATE TABLE tenant_invitation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    code       VARCHAR(255),
    invited_by BIGINT,
    expire_at  TIMESTAMP WITHOUT TIME ZONE,
    role       VARCHAR(255),
    CONSTRAINT pk_tenant_invitation PRIMARY KEY (id)
);

ALTER TABLE tenant_invitation
    ADD CONSTRAINT FK_TENANT_INVITATION_ON_INVITED_BY FOREIGN KEY (invited_by) REFERENCES tenant_users (id);