CREATE TABLE service_area
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    technician_id BIGINT,
    biller_id     BIGINT,
    area_id       BIGINT,
    CONSTRAINT pk_service_area PRIMARY KEY (id)
);

ALTER TABLE service_area
    ADD CONSTRAINT FK_SERVICE_AREA_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id);

ALTER TABLE service_area
    ADD CONSTRAINT FK_SERVICE_AREA_ON_BILLER FOREIGN KEY (biller_id) REFERENCES platform_users (id);

ALTER TABLE service_area
    ADD CONSTRAINT FK_SERVICE_AREA_ON_TECHNICIAN FOREIGN KEY (technician_id) REFERENCES platform_users (id);